### PR TITLE
spotify `1.1.78`, `1.1.77` and `1.1.76`

### PR DESCRIPTION
**Pull request by machinemessiah**

### CODE REVIEW

**Comment by afonsojramos** [comment]
No need to detail after the minor.
We only need the `1.1.X` in my opinion.

**Comment by machinemessiah** [comment]
> No need to detail after the minor. We only need the `1.1.X` in my opinion.

Agreed, I've trimmed them down.

**Comment by afonsojramos** [comment]
I believe we don't need the `.zip` files either, right?

The vendor ones are the ones from the `Raw` folder I assume?

**Comment by machinemessiah** [comment]
> I believe we don't need the `.zip` files either, right?
> 
> The vendor ones are the ones from the `Raw` folder I assume?

I just used a sandbox (in windows) to install Spotify v1.1.XX, grab `AppData\Roaming\Spotify\Apps\xpui.spa`, then uninstall (rinse and repeat).

So the files I've added for each version are just extracted from the xpui.spa archive, which is how I assume Spicetify gets those files/folders in the first place.

**Comment by afonsojramos** [comment]
Yes, but I was referring to the fact that you included said xpui.spa.zip archive for some of the files.

**Comment by machinemessiah** [comment]
> Yes, but I was referring to the fact that you included said xpui.spa.zip archive for some of the files.

Sorry, didn't notice your comment until now.

It was a case of me thinking "What do we actually **need** to archive?" 
Expanding on that: which files - _and in what format(s)_ - are actually going to serve a purpose beyond simply being available in a convenient location?

The xpui.spa.zip (the zip extension isn't actually necessary) files contain everything that might be useful to check against if a future update cripples Spicetify, so should we just archive those for each Spotify version, or is it worthwhile to have the contents (xpui.js,xpui.css, the vendor js/css) viewable as js/css without someone having to download and extract the .spa archive?

It's the reason why I was wondering whether it would be useful to add those extracted js/css files to the main repo, then following that, commit those same files after each Spotify patch/update - just so we have a readable history of what changes have been made, which hopefully would make updating the regex a little easier in the future.

**I'm rambling. I'll get rid of the redundant .spa.zip files in the meantime.**
Let me know if you have any thoughts regarding my spiel.

**Comment by afonsojramos** [comment]
I wanted @CharlieS1103 to approve this but I guess he isn't paying attention to his GitHub notifications 👀

**Review by afonsojramos — APPROVED** [review]

**Pull request merged**
